// Generated by https://quicktype.io

export interface ReportModel {
  id:             string;
  collectionId:   string;
  collectionName: string;
  created:        string;
  updated:        string;
  maths:          number;
  science:        number;
  english:        number;
  student_id:     string;
}
